site_name: scimpler
site_description: simpler SCIM integrations
site_author: Arkadiusz Pajor
repo_url: https://github.com/Pagerous/scimple
repo_name: scimpler
nav:
  - Introduction: index.md
  - User's Guide: users_guide.md
  - API Reference: api_reference.md
theme: material
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences