site_name: scimple
nav:
  - Home: index.md
  - About: about.md
theme: material
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google